import { useState, type FormEvent, type ReactNode } from 'react'
import { ArrowLeft, ArrowRight, BarChart3, Check, Eye, EyeOff, LockKeyhole, Package, ShieldCheck, Sparkles } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { apiMessage } from '../services/api'
import { authService } from '../services/auth'
import { Button, Field, Input } from '../components/ui'

function AuthFrame({ children, heading, text, step }: { children: ReactNode; heading: string; text: string; step?: string }) {
  return <div className="auth-grid min-h-screen bg-[#f7f8fc] lg:grid lg:grid-cols-[1fr_1fr]">
    <div className="relative hidden min-h-screen overflow-hidden bg-[#111a34] px-12 py-10 text-white lg:flex lg:flex-col xl:px-20"><Link to="/login" className="relative z-10 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-500"><Package size={21} /></span><span className="font-[Manrope] text-xl font-extrabold tracking-tight">stocksense</span></Link><div className="relative z-10 my-auto max-w-xl py-20"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[.06] px-3 py-1.5 text-xs text-indigo-100"><Sparkles size={14} className="text-teal-300" /> A clearer view of your inventory</div><h2 className="font-[Manrope] text-5xl font-bold leading-[1.12] tracking-tight xl:text-[56px]">Make every<br />stock decision<br /><span className="text-indigo-300">a smart one.</span></h2><p className="mt-6 max-w-md text-base leading-7 text-slate-300">Bring products, warehouses, and daily operations into one calm, connected workspace.</p><div className="mt-12 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-white/[.055] p-4"><BarChart3 className="mb-4 text-teal-300" size={20} /><p className="text-sm font-semibold">See the whole picture</p><p className="mt-1 text-xs text-slate-400">Live inventory signals, at a glance.</p></div><div className="rounded-xl border border-white/10 bg-white/[.055] p-4"><ShieldCheck className="mb-4 text-indigo-300" size={20} /><p className="text-sm font-semibold">Move with confidence</p><p className="mt-1 text-xs text-slate-400">Every stock movement, accounted for.</p></div></div></div><div className="relative z-10 flex justify-between text-xs text-slate-500"><span>© 2026 StockSense</span><span>Inventory, in focus.</span></div><div className="pointer-events-none absolute -bottom-32 -right-28 h-96 w-96 rounded-full border border-white/[.07]" /><div className="pointer-events-none absolute -bottom-20 -right-16 h-72 w-72 rounded-full border border-white/[.07]" /></div>
    <div className="flex min-h-screen flex-col px-5 py-7 sm:px-10 lg:justify-center lg:px-12 xl:px-24"><div className="mx-auto w-full max-w-[430px]"><Link to="/login" className="mb-10 inline-flex items-center gap-2 font-[Manrope] text-lg font-extrabold text-ink lg:hidden"><span className="grid h-9 w-9 place-items-center rounded-lg bg-brand-600 text-white"><Package size={18} /></span>stocksense</Link>{step && <p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-brand-600">{step}</p>}<h1 className="font-[Manrope] text-[30px] font-bold tracking-tight text-ink">{heading}</h1><p className="mt-2 text-sm leading-6 text-muted">{text}</p><div className="mt-8">{children}</div><p className="mt-10 text-center text-xs text-slate-400">Securely connected to your StockSense workspace</p></div></div>
  </div>
}

function PasswordField({ label = 'Password', name = label.toLowerCase().replace(/ /g, '-'), autoComplete = 'current-password' }: { label?: string; name?: string; autoComplete?: string }) {
  const [shown, setShown] = useState(false)
  return <Field label={label}><span className="relative block"><Input type={shown ? 'text' : 'password'} name={name} autoComplete={autoComplete} required minLength={8} placeholder="At least 8 characters" className="pr-11" /><button type="button" onClick={() => setShown(!shown)} aria-label={shown ? 'Hide password' : 'Show password'} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-ink">{shown ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></Field>
}

export function LoginPage() {
  const { login } = useAuth(); const { notify } = useToast(); const navigate = useNavigate(); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const data = new FormData(event.currentTarget); try { await login(String(data.get('email')), String(data.get('password'))); navigate('/dashboard', { replace: true }) } catch (error) { notify(apiMessage(error), 'error') } finally { setLoading(false) } }
  return <AuthFrame heading="Welcome back" text="Sign in to your workspace and pick up right where you left off."><form className="space-y-5" onSubmit={submit}><Field label="Work email"><Input name="email" type="email" required autoComplete="email" placeholder="you@company.com" /></Field><PasswordField /><div className="-mt-1 flex justify-end"><Link to="/forgot-password" className="text-sm font-semibold text-brand-600 hover:text-brand-700">Forgot password?</Link></div><Button className="w-full" loading={loading} type="submit">Sign in <ArrowRight size={16} /></Button><p className="pt-2 text-center text-sm text-muted">New to StockSense? <Link className="font-semibold text-brand-600 hover:text-brand-700" to="/signup">Create an account</Link></p></form></AuthFrame>
}

export function SignupPage() {
  const { register } = useAuth(); const { notify } = useToast(); const navigate = useNavigate(); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const data = new FormData(event.currentTarget); const password = String(data.get('password')); if (password !== data.get('confirm-password')) { notify('Passwords do not match.', 'error'); setLoading(false); return } try { await register(String(data.get('name')), String(data.get('email')), password); notify('Your account is ready.'); navigate('/dashboard', { replace: true }) } catch (error) { notify(apiMessage(error), 'error') } finally { setLoading(false) } }
  return <AuthFrame heading="Create your account" text="Set up your workspace to start managing inventory with clarity."><form className="space-y-4" onSubmit={submit}><Field label="Your name"><Input name="name" required autoComplete="name" placeholder="Alex Morgan" /></Field><Field label="Work email"><Input name="email" type="email" required autoComplete="email" placeholder="you@company.com" /></Field><PasswordField label="Create password" name="password" autoComplete="new-password" /><PasswordField label="Confirm password" name="confirm-password" autoComplete="new-password" /><p className="-mt-1 text-xs text-muted"><Check className="mr-1 inline text-emerald-500" size={14} />Use at least 8 characters.</p><Button className="mt-2 w-full" loading={loading} type="submit">Create account <ArrowRight size={16} /></Button><p className="pt-2 text-center text-sm text-muted">Already have an account? <Link className="font-semibold text-brand-600" to="/login">Sign in</Link></p></form></AuthFrame>
}

export function ForgotPasswordPage() {
  const { notify } = useToast(); const navigate = useNavigate(); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const email = String(new FormData(event.currentTarget).get('email')); try { const result = await authService.forgotPassword(email); sessionStorage.setItem('stocksense_reset_email', email); sessionStorage.setItem('stocksense_reset_dev_otp', result.devOtp ?? ''); notify(result.devOtp ? `Development reset code: ${result.devOtp}` : result.message, 'info'); navigate('/verify-otp') } catch (error) { notify(apiMessage(error), 'error') } finally { setLoading(false) } }
  return <AuthFrame step="Account recovery" heading="Forgot your password?" text="Enter the email linked to your account. We'll send a one-time code to verify it's you."><form onSubmit={submit} className="space-y-5"><Field label="Work email"><Input type="email" name="email" autoComplete="email" required placeholder="you@company.com" /></Field><Button className="w-full" type="submit" loading={loading}>Send verification code <ArrowRight size={16} /></Button><Link to="/login" className="flex items-center justify-center gap-2 pt-2 text-sm font-semibold text-muted hover:text-ink"><ArrowLeft size={15} /> Back to sign in</Link></form></AuthFrame>
}

export function VerifyOtpPage() {
  const { notify } = useToast(); const navigate = useNavigate(); const [loading, setLoading] = useState(false); const email = sessionStorage.getItem('stocksense_reset_email') ?? ''; const devOtp = sessionStorage.getItem('stocksense_reset_dev_otp') ?? ''
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const otp = String(new FormData(event.currentTarget).get('otp')); try { await authService.verifyOtp({ email, otp }); sessionStorage.setItem('stocksense_reset_otp', otp); navigate('/reset-password') } catch (error) { notify(apiMessage(error), 'error') } finally { setLoading(false) } }
  async function resend() { if (!email) { navigate('/forgot-password'); return } setLoading(true); try { const result = await authService.forgotPassword(email); sessionStorage.setItem('stocksense_reset_dev_otp', result.devOtp ?? ''); notify(result.devOtp ? `Development reset code: ${result.devOtp}` : result.message, 'info') } catch (error) { notify(apiMessage(error), 'error') } finally { setLoading(false) } }
  return <AuthFrame step="Account recovery · 02" heading="Check your inbox" text={email ? `Enter the 6-digit verification code for ${email}.` : 'Enter the verification code sent to your email.'}><form onSubmit={(event) => void submit(event)} className="space-y-5"><Field label="Verification code"><Input name="otp" required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="000000" className="text-center text-xl tracking-[.35em]" /></Field>{devOtp && <p className="rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-800">Development OTP from the API: <b className="tracking-widest">{devOtp}</b></p>}<p className="text-xs text-muted">The server verifies this code before allowing a password reset.</p><Button className="w-full" type="submit" loading={loading}>Continue <ArrowRight size={16} /></Button><button type="button" disabled={loading} className="w-full text-sm font-semibold text-brand-600 disabled:opacity-50" onClick={() => void resend()}>Resend code</button><Link to="/forgot-password" className="flex items-center justify-center gap-2 pt-1 text-sm text-muted"><ArrowLeft size={15} /> Change email</Link></form></AuthFrame>
}

export function ResetPasswordPage() {
  const { notify } = useToast(); const { logout } = useAuth(); const navigate = useNavigate(); const [loading, setLoading] = useState(false); const email = sessionStorage.getItem('stocksense_reset_email') ?? ''; const otp = sessionStorage.getItem('stocksense_reset_otp') ?? ''
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const data = new FormData(event.currentTarget); const password = String(data.get('newPassword')); if (password !== data.get('confirmPassword')) { notify('Passwords do not match.', 'error'); setLoading(false); return } try { await authService.resetPassword({ email, otp, newPassword: password }); await logout(); sessionStorage.removeItem('stocksense_reset_email'); sessionStorage.removeItem('stocksense_reset_otp'); sessionStorage.removeItem('stocksense_reset_dev_otp'); notify('Your password has been updated.'); navigate('/login') } catch (error) { notify(apiMessage(error), 'error') } finally { setLoading(false) } }
  return <AuthFrame step="Account recovery · 03" heading="Create a new password" text="Choose a strong password you haven't used before."><form onSubmit={submit} className="space-y-5"><PasswordField label="New password" name="newPassword" autoComplete="new-password" /><PasswordField label="Confirm new password" name="confirmPassword" autoComplete="new-password" /><Button className="w-full" type="submit" loading={loading}><LockKeyhole size={16} /> Update password</Button><Link to="/login" className="flex items-center justify-center gap-2 pt-1 text-sm text-muted"><ArrowLeft size={15} /> Back to sign in</Link></form></AuthFrame>
}
