import { useCallback, useMemo, useState, type FormEvent } from 'react'
import { Building2, Mail, MapPin, Pencil, Phone, Plus, Search, Tag, Trash2, Truck } from 'lucide-react'
import { categoryService } from '../services/category'
import { warehouseService } from '../services/warehouse'
import { locationService } from '../services/location'
import { resourceService } from '../services/resources'
import type { Entity } from '../services/types'
import { apiMessage } from '../services/api'
import { useRemote } from '../hooks/useRemote'
import { useToast } from '../context/ToastContext'
import { Button, Card, EmptyState, ErrorState, Field, Input, Modal, PageHeader, Select, Spinner } from '../components/ui'

type DirectoryKind = 'categories' | 'warehouses' | 'locations' | 'suppliers' | 'customers'
const serviceByKind = { categories: categoryService, warehouses: warehouseService, locations: locationService, suppliers: resourceService('suppliers'), customers: resourceService('customers') }
const config: Record<DirectoryKind, { title: string; singular: string; description: string; fields: { name: string; label: string; type?: string; required?: boolean }[]; icon: typeof Tag }> = {
  categories: { title: 'Categories', singular: 'category', description: 'Group products into clear, useful categories.', fields: [{ name: 'name', label: 'Category name', required: true }, { name: 'description', label: 'Description' }], icon: Tag },
  warehouses: { title: 'Warehouses', singular: 'warehouse', description: 'Manage the buildings that contain your stock locations.', fields: [{ name: 'name', label: 'Warehouse name', required: true }, { name: 'code', label: 'Warehouse code' }, { name: 'address', label: 'Address' }], icon: Building2 },
  locations: { title: 'Stock locations', singular: 'location', description: 'Create stock locations inside warehouses for receipts, deliveries, and inventory counts.', fields: [{ name: 'name', label: 'Location name', required: true }, { name: 'code', label: 'Location code', required: true }, { name: 'warehouseId', label: 'Warehouse', required: true }], icon: MapPin },
  suppliers: { title: 'Suppliers', singular: 'supplier', description: 'Keep supplier contact details close to your receipts.', fields: [{ name: 'name', label: 'Supplier name', required: true }, { name: 'contactPerson', label: 'Contact person' }, { name: 'email', label: 'Email', type: 'email' }, { name: 'phone', label: 'Phone', type: 'tel' }, { name: 'address', label: 'Address' }], icon: Truck },
  customers: { title: 'Customers', singular: 'customer', description: 'Manage customer records for outbound deliveries.', fields: [{ name: 'name', label: 'Customer name', required: true }, { name: 'contactPerson', label: 'Contact person' }, { name: 'email', label: 'Email', type: 'email' }, { name: 'phone', label: 'Phone', type: 'tel' }, { name: 'address', label: 'Address' }], icon: Building2 },
}

function DirectoryForm({ kind, item, warehouses, onCancel, onSave }: { kind: DirectoryKind; item?: Entity; warehouses: Entity[]; onCancel: () => void; onSave: (payload: Record<string, unknown>) => Promise<void> }) {
  const [loading, setLoading] = useState(false); const fields = config[kind].fields
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const data = new FormData(event.currentTarget); const payload: Record<string, unknown> = {}; fields.forEach((field) => { const value = data.get(field.name); if (value !== '') payload[field.name] = field.type === 'number' || field.name === 'warehouseId' ? Number(value) : value }); try { await onSave(payload) } catch { /* save failures are announced by the parent */ } finally { setLoading(false) } }
  return <form onSubmit={(event) => void submit(event)} className="space-y-4">{fields.map((field) => <Field key={field.name} label={field.label}>{field.name === 'warehouseId' ? <Select name={field.name} required defaultValue={String(item?.warehouseId ?? '')}><option value="" disabled>Select a warehouse</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</Select> : field.name === 'description' || field.name === 'address' || field.name === 'location' ? <textarea name={field.name} rows={2} defaultValue={String(item?.[field.name] ?? '')} required={field.required} placeholder={field.label} className="w-full rounded-lg border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-brand-500 focus:ring-4 focus:ring-brand-500/10" /> : <Input name={field.name} type={field.type ?? 'text'} required={field.required} defaultValue={String(item?.[field.name] ?? '')} placeholder={field.label} min={field.type === 'number' ? 0 : undefined} />}</Field>)}<div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" loading={loading}>{item ? 'Save changes' : `Add ${config[kind].singular}`}</Button></div></form>
}

export function DirectoryPage({ kind }: { kind: DirectoryKind }) {
  const configItem = config[kind]; const service = serviceByKind[kind]; const request = useCallback(() => service.list(), [service]); const result = useRemote(request)
  const warehouses = useRemote(warehouseService.list)
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Entity | null | undefined>(undefined); const { notify } = useToast()
  const rows = useMemo(() => (result.data ?? []).filter((item) => `${item.name ?? ''} ${item.code ?? ''} ${item.email ?? ''} ${item.location ?? item.address ?? ''}`.toLowerCase().includes(query.toLowerCase())), [result.data, query])
  async function save(payload: Record<string, unknown>) { try { if (editing) await service.update(editing.id, payload); else await service.create(payload); notify(`${configItem.singular[0].toUpperCase()}${configItem.singular.slice(1)} ${editing ? 'updated' : 'created'}.`); setEditing(undefined); result.retry() } catch (error) { notify(apiMessage(error), 'error'); throw error } }
  async function remove(item: Entity) { if (!window.confirm(`Delete ${item.name ?? configItem.singular}? This cannot be undone.`)) return; try { await service.remove(item.id); notify(`${configItem.singular} deleted.`); result.retry() } catch (error) { notify(apiMessage(error), 'error') } }
  const Icon = configItem.icon
  return <div><PageHeader eyebrow="Workspace setup" title={configItem.title} description={configItem.description} action={<Button onClick={() => setEditing(null)}><Plus size={17} /> Add {configItem.singular}</Button>} />
    <Card><div className="border-b border-slate-100 p-4"><div className="relative max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${configItem.title.toLowerCase()}`} className="pl-9" /></div></div>
      {result.loading ? <Spinner label={`Loading ${configItem.title.toLowerCase()}`} /> : result.error ? <ErrorState message={result.error} onRetry={result.retry} /> : rows.length === 0 ? <EmptyState title={`No ${configItem.title.toLowerCase()} found`} description={`Add your first ${configItem.singular} or try another search.`} /> : <div className="divide-y divide-slate-100">{rows.map((item) => <div key={item.id} className="group flex items-center gap-4 px-5 py-4 hover:bg-slate-50/70"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-50 text-brand-600"><Icon size={19} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2"><p className="truncate text-sm font-semibold text-ink">{item.name ?? 'Unnamed record'}</p>{item.code && <span className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] font-medium text-slate-500">{item.code}</span>}</div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted">{item.contactPerson && <span>Contact: {item.contactPerson}</span>}{item.email && <span className="inline-flex items-center gap-1"><Mail size={12} />{item.email}</span>}{item.phone && <span className="inline-flex items-center gap-1"><Phone size={12} />{item.phone}</span>}{(item.location ?? item.address) && <span className="inline-flex items-center gap-1"><MapPin size={12} />{String(item.location ?? item.address)}</span>}{item.description && <span className="truncate">{item.description}</span>}</div></div><div className="flex gap-1"><button title={`Edit ${configItem.singular}`} onClick={() => setEditing(item)} className="rounded-lg p-2 text-slate-400 hover:bg-indigo-50 hover:text-brand-600"><Pencil size={16} /></button><button title={`Delete ${configItem.singular}`} onClick={() => void remove(item)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16} /></button></div></div>)}</div>}
      {!result.loading && !result.error && rows.length > 0 && <div className="border-t border-slate-100 px-5 py-3 text-xs text-muted">{rows.length} {configItem.title.toLowerCase()}</div>}
    </Card>
    {editing !== undefined && <Modal title={editing ? `Edit ${configItem.singular}` : `Add ${configItem.singular}`} onClose={() => setEditing(undefined)}>{kind === 'locations' && (warehouses.loading || warehouses.error) ? warehouses.loading ? <Spinner label="Loading warehouses" /> : <ErrorState message={warehouses.error ?? 'Could not load warehouses.'} onRetry={warehouses.retry} /> : <DirectoryForm kind={kind} item={editing ?? undefined} warehouses={warehouses.data ?? []} onCancel={() => setEditing(undefined)} onSave={save} />}</Modal>}
  </div>
}
